#!/bin/bash

# Test script for multisig functionality

set -e

CLI="./target/debug/opensyria-node-cli"
TEST_DIR="/tmp/opensyria-multisig-test"

echo "════════════════════════════════════════════════════════════"
echo "  Multisig Account Test"
echo "════════════════════════════════════════════════════════════"
echo

# Clean up previous test data
rm -rf "$TEST_DIR"
mkdir -p "$TEST_DIR"

# Initialize node
echo "1. Initializing blockchain..."
$CLI -d "$TEST_DIR" init --difficulty 12 > /dev/null
echo "✓ Blockchain initialized"
echo

# Generate random 32-byte hex keys (for testing purposes only)
echo "2. Generating test keypairs..."
SIGNER1_PRIV=$(openssl rand -hex 32)
SIGNER2_PRIV=$(openssl rand -hex 32)
SIGNER3_PRIV=$(openssl rand -hex 32)

# Derive public keys (simplified - using hash for demo)
SIGNER1_PUB=$(echo -n "$SIGNER1_PRIV" | sha256sum | cut -d' ' -f1)
SIGNER2_PUB=$(echo -n "$SIGNER2_PRIV" | sha256sum | cut -d' ' -f1)
SIGNER3_PUB=$(echo -n "$SIGNER3_PRIV" | sha256sum | cut -d' ' -f1)
RECIPIENT_PUB=$(openssl rand -hex 32)

echo "✓ Generated 3 signer keypairs + 1 recipient"
echo "  Signer 1: ${SIGNER1_PUB:0:16}..."
echo "  Signer 2: ${SIGNER2_PUB:0:16}..."
echo "  Signer 3: ${SIGNER3_PUB:0:16}..."
echo

echo "3. Creating 2-of-3 multisig account..."
OUTPUT=$($CLI -d "$TEST_DIR" multisig create \
  --signer "$SIGNER1_PUB" \
  --signer "$SIGNER2_PUB" \
  --signer "$SIGNER3_PUB" \
  --threshold 2 \
  --balance 10000000)

echo "$OUTPUT"
MULTISIG_ADDR=$(echo "$OUTPUT" | grep "Address:" | awk '{print $2}')
echo

echo "4. Checking multisig account info..."
$CLI -d "$TEST_DIR" multisig info "$MULTISIG_ADDR"
echo

echo "════════════════════════════════════════════════════════════"
echo "  ✓ Multisig Account Creation Test Passed"
echo "════════════════════════════════════════════════════════════"
echo
echo "Note: Transaction signing test requires proper Ed25519 keypairs"
echo "      which are generated by the wallet CLI."

